/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/scanner.glb --types --metadata --print 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    g_grp1: THREE.Mesh
    g_grp45283: THREE.Mesh
    g_grp183771: THREE.Mesh
    g_grp211379: THREE.Mesh
    g_grp211627: THREE.Mesh
    g_grp484753: THREE.Mesh
    g_grp739439: THREE.Mesh
    g_grp949079: THREE.Mesh
    g_grp1080247: THREE.Mesh
    g_grp1340787: THREE.Mesh
    g_grp1375405: THREE.Mesh
    g_grp1406667: THREE.Mesh
    g_grp1420465: THREE.Mesh
    g_grp1445565: THREE.Mesh
    g_grp1474193: THREE.Mesh
    g_grp1502293: THREE.Mesh
    g_grp1528587: THREE.Mesh
    g_grp1552983: THREE.Mesh
    g_grp1576677: THREE.Mesh
    g_grp1600241: THREE.Mesh
    g_grp1622949: THREE.Mesh
    g_grp1644091: THREE.Mesh
    g_grp1664815: THREE.Mesh
    g_grp1686189: THREE.Mesh
    g_grp1706515: THREE.Mesh
    g_grp1724105: THREE.Mesh
    g_grp1735659: THREE.Mesh
    g_grp1736171: THREE.Mesh
    g_grp1877203: THREE.Mesh
    g_grp1953509: THREE.Mesh
    g_grp1975805: THREE.Mesh
    g_grp1980065: THREE.Mesh
    g_grp1989391: THREE.Mesh
    g_grp1999901: THREE.Mesh
    g_grp2005311: THREE.Mesh
    g_grp2012287: THREE.Mesh
    g_grp2024819: THREE.Mesh
    g_grp2031229: THREE.Mesh
    g_grp2037745: THREE.Mesh
    g_grp2048789: THREE.Mesh
    g_grp2068877: THREE.Mesh
    g_grp2073809: THREE.Mesh
    g_grp2105837: THREE.Mesh
    g_grp2137105: THREE.Mesh
    g_grp2252781: THREE.Mesh
    g_grp2372991: THREE.Mesh
    g_grp2395957: THREE.Mesh
    g_grp2420439: THREE.Mesh
    g_grp2468825: THREE.Mesh
    g_grp2582995: THREE.Mesh
    g_grp2697673: THREE.Mesh
    g_grp2712091: THREE.Mesh
    g_grp2731331: THREE.Mesh
    g_grp2753941: THREE.Mesh
    g_grp2782195: THREE.Mesh
    g_grp2810849: THREE.Mesh
    g_grp2839741: THREE.Mesh
    g_grp2870957: THREE.Mesh
    g_grp2897319: THREE.Mesh
    g_grp2917671: THREE.Mesh
    g_grp2932557: THREE.Mesh
    g_grp2939795: THREE.Mesh
    g_grp2941121: THREE.Mesh
    g_grp2956517: THREE.Mesh
    g_grp2974647: THREE.Mesh
    g_grp2998077: THREE.Mesh
    g_grp3024567: THREE.Mesh
    g_grp3054561: THREE.Mesh
    g_grp3084917: THREE.Mesh
    g_grp3116927: THREE.Mesh
    g_grp3145355: THREE.Mesh
    g_grp3167707: THREE.Mesh
    g_grp3183233: THREE.Mesh
    g_grp3191281: THREE.Mesh
    g_grp3192149: THREE.Mesh
    g_grp3236631: THREE.Mesh
  }
  materials: {
    mtl1: THREE.MeshStandardMaterial
    mtl45283: THREE.MeshStandardMaterial
    mtl183771: THREE.MeshStandardMaterial
    mtl211379: THREE.MeshStandardMaterial
    mtl211627: THREE.MeshStandardMaterial
    mtl484753: THREE.MeshStandardMaterial
    mtl739439: THREE.MeshStandardMaterial
    mtl949079: THREE.MeshStandardMaterial
    mtl1080247: THREE.MeshStandardMaterial
    mtl1340787: THREE.MeshStandardMaterial
    mtl1375405: THREE.MeshStandardMaterial
    mtl1406667: THREE.MeshStandardMaterial
    mtl1420465: THREE.MeshStandardMaterial
    mtl1445565: THREE.MeshStandardMaterial
    mtl1474193: THREE.MeshStandardMaterial
    mtl1502293: THREE.MeshStandardMaterial
    mtl1528587: THREE.MeshStandardMaterial
    mtl1552983: THREE.MeshStandardMaterial
    mtl1576677: THREE.MeshStandardMaterial
    mtl1600241: THREE.MeshStandardMaterial
    mtl1622949: THREE.MeshStandardMaterial
    mtl1644091: THREE.MeshStandardMaterial
    mtl1664815: THREE.MeshStandardMaterial
    mtl1686189: THREE.MeshStandardMaterial
    mtl1706515: THREE.MeshStandardMaterial
    mtl1724105: THREE.MeshStandardMaterial
    mtl1735659: THREE.MeshStandardMaterial
    mtl1736171: THREE.MeshStandardMaterial
    mtl1877203: THREE.MeshStandardMaterial
    mtl1953509: THREE.MeshStandardMaterial
    mtl1975805: THREE.MeshStandardMaterial
    mtl1980065: THREE.MeshStandardMaterial
    mtl1989391: THREE.MeshStandardMaterial
    mtl1999901: THREE.MeshStandardMaterial
    mtl2005311: THREE.MeshStandardMaterial
    mtl2012287: THREE.MeshStandardMaterial
    mtl2024819: THREE.MeshStandardMaterial
    mtl2031229: THREE.MeshStandardMaterial
    mtl2037745: THREE.MeshStandardMaterial
    mtl2048789: THREE.MeshStandardMaterial
    mtl2068877: THREE.MeshStandardMaterial
    mtl2073809: THREE.MeshStandardMaterial
    mtl2105837: THREE.MeshStandardMaterial
    mtl2137105: THREE.MeshStandardMaterial
    mtl2252781: THREE.MeshStandardMaterial
    mtl2372991: THREE.MeshStandardMaterial
    mtl2395957: THREE.MeshStandardMaterial
    mtl2420439: THREE.MeshStandardMaterial
    mtl2468825: THREE.MeshStandardMaterial
    mtl2582995: THREE.MeshStandardMaterial
    mtl2697673: THREE.MeshStandardMaterial
    mtl2712091: THREE.MeshStandardMaterial
    mtl2731331: THREE.MeshStandardMaterial
    mtl2753941: THREE.MeshStandardMaterial
    mtl2782195: THREE.MeshStandardMaterial
    mtl2810849: THREE.MeshStandardMaterial
    mtl2839741: THREE.MeshStandardMaterial
    mtl2870957: THREE.MeshStandardMaterial
    mtl2897319: THREE.MeshStandardMaterial
    mtl2917671: THREE.MeshStandardMaterial
    mtl2932557: THREE.MeshStandardMaterial
    mtl2939795: THREE.MeshStandardMaterial
    mtl2941121: THREE.MeshStandardMaterial
    mtl2956517: THREE.MeshStandardMaterial
    mtl2974647: THREE.MeshStandardMaterial
    mtl2998077: THREE.MeshStandardMaterial
    mtl3024567: THREE.MeshStandardMaterial
    mtl3054561: THREE.MeshStandardMaterial
    mtl3084917: THREE.MeshStandardMaterial
    mtl3116927: THREE.MeshStandardMaterial
    mtl3145355: THREE.MeshStandardMaterial
    mtl3167707: THREE.MeshStandardMaterial
    mtl3183233: THREE.MeshStandardMaterial
    mtl3191281: THREE.MeshStandardMaterial
    mtl3192149: THREE.MeshStandardMaterial
    mtl3236631: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scanner.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.g_grp1.geometry} material={materials.mtl1} />
      <mesh geometry={nodes.g_grp45283.geometry} material={materials.mtl45283} />
      <mesh geometry={nodes.g_grp183771.geometry} material={materials.mtl183771} />
      <mesh geometry={nodes.g_grp211379.geometry} material={materials.mtl211379} />
      <mesh geometry={nodes.g_grp211627.geometry} material={materials.mtl211627} />
      <mesh geometry={nodes.g_grp484753.geometry} material={materials.mtl484753} />
      <mesh geometry={nodes.g_grp739439.geometry} material={materials.mtl739439} />
      <mesh geometry={nodes.g_grp949079.geometry} material={materials.mtl949079} />
      <mesh geometry={nodes.g_grp1080247.geometry} material={materials.mtl1080247} />
      <mesh geometry={nodes.g_grp1340787.geometry} material={materials.mtl1340787} />
      <mesh geometry={nodes.g_grp1375405.geometry} material={materials.mtl1375405} />
      <mesh geometry={nodes.g_grp1406667.geometry} material={materials.mtl1406667} />
      <mesh geometry={nodes.g_grp1420465.geometry} material={materials.mtl1420465} />
      <mesh geometry={nodes.g_grp1445565.geometry} material={materials.mtl1445565} />
      <mesh geometry={nodes.g_grp1474193.geometry} material={materials.mtl1474193} />
      <mesh geometry={nodes.g_grp1502293.geometry} material={materials.mtl1502293} />
      <mesh geometry={nodes.g_grp1528587.geometry} material={materials.mtl1528587} />
      <mesh geometry={nodes.g_grp1552983.geometry} material={materials.mtl1552983} />
      <mesh geometry={nodes.g_grp1576677.geometry} material={materials.mtl1576677} />
      <mesh geometry={nodes.g_grp1600241.geometry} material={materials.mtl1600241} />
      <mesh geometry={nodes.g_grp1622949.geometry} material={materials.mtl1622949} />
      <mesh geometry={nodes.g_grp1644091.geometry} material={materials.mtl1644091} />
      <mesh geometry={nodes.g_grp1664815.geometry} material={materials.mtl1664815} />
      <mesh geometry={nodes.g_grp1686189.geometry} material={materials.mtl1686189} />
      <mesh geometry={nodes.g_grp1706515.geometry} material={materials.mtl1706515} />
      <mesh geometry={nodes.g_grp1724105.geometry} material={materials.mtl1724105} />
      <mesh geometry={nodes.g_grp1735659.geometry} material={materials.mtl1735659} />
      <mesh geometry={nodes.g_grp1736171.geometry} material={materials.mtl1736171} />
      <mesh geometry={nodes.g_grp1877203.geometry} material={materials.mtl1877203} />
      <mesh geometry={nodes.g_grp1953509.geometry} material={materials.mtl1953509} />
      <mesh geometry={nodes.g_grp1975805.geometry} material={materials.mtl1975805} />
      <mesh geometry={nodes.g_grp1980065.geometry} material={materials.mtl1980065} />
      <mesh geometry={nodes.g_grp1989391.geometry} material={materials.mtl1989391} />
      <mesh geometry={nodes.g_grp1999901.geometry} material={materials.mtl1999901} />
      <mesh geometry={nodes.g_grp2005311.geometry} material={materials.mtl2005311} />
      <mesh geometry={nodes.g_grp2012287.geometry} material={materials.mtl2012287} />
      <mesh geometry={nodes.g_grp2024819.geometry} material={materials.mtl2024819} />
      <mesh geometry={nodes.g_grp2031229.geometry} material={materials.mtl2031229} />
      <mesh geometry={nodes.g_grp2037745.geometry} material={materials.mtl2037745} />
      <mesh geometry={nodes.g_grp2048789.geometry} material={materials.mtl2048789} />
      <mesh geometry={nodes.g_grp2068877.geometry} material={materials.mtl2068877} />
      <mesh geometry={nodes.g_grp2073809.geometry} material={materials.mtl2073809} />
      <mesh geometry={nodes.g_grp2105837.geometry} material={materials.mtl2105837} />
      <mesh geometry={nodes.g_grp2137105.geometry} material={materials.mtl2137105} />
      <mesh geometry={nodes.g_grp2252781.geometry} material={materials.mtl2252781} />
      <mesh geometry={nodes.g_grp2372991.geometry} material={materials.mtl2372991} />
      <mesh geometry={nodes.g_grp2395957.geometry} material={materials.mtl2395957} />
      <mesh geometry={nodes.g_grp2420439.geometry} material={materials.mtl2420439} />
      <mesh geometry={nodes.g_grp2468825.geometry} material={materials.mtl2468825} />
      <mesh geometry={nodes.g_grp2582995.geometry} material={materials.mtl2582995} />
      <mesh geometry={nodes.g_grp2697673.geometry} material={materials.mtl2697673} />
      <mesh geometry={nodes.g_grp2712091.geometry} material={materials.mtl2712091} />
      <mesh geometry={nodes.g_grp2731331.geometry} material={materials.mtl2731331} />
      <mesh geometry={nodes.g_grp2753941.geometry} material={materials.mtl2753941} />
      <mesh geometry={nodes.g_grp2782195.geometry} material={materials.mtl2782195} />
      <mesh geometry={nodes.g_grp2810849.geometry} material={materials.mtl2810849} />
      <mesh geometry={nodes.g_grp2839741.geometry} material={materials.mtl2839741} />
      <mesh geometry={nodes.g_grp2870957.geometry} material={materials.mtl2870957} />
      <mesh geometry={nodes.g_grp2897319.geometry} material={materials.mtl2897319} />
      <mesh geometry={nodes.g_grp2917671.geometry} material={materials.mtl2917671} />
      <mesh geometry={nodes.g_grp2932557.geometry} material={materials.mtl2932557} />
      <mesh geometry={nodes.g_grp2939795.geometry} material={materials.mtl2939795} />
      <mesh geometry={nodes.g_grp2941121.geometry} material={materials.mtl2941121} />
      <mesh geometry={nodes.g_grp2956517.geometry} material={materials.mtl2956517} />
      <mesh geometry={nodes.g_grp2974647.geometry} material={materials.mtl2974647} />
      <mesh geometry={nodes.g_grp2998077.geometry} material={materials.mtl2998077} />
      <mesh geometry={nodes.g_grp3024567.geometry} material={materials.mtl3024567} />
      <mesh geometry={nodes.g_grp3054561.geometry} material={materials.mtl3054561} />
      <mesh geometry={nodes.g_grp3084917.geometry} material={materials.mtl3084917} />
      <mesh geometry={nodes.g_grp3116927.geometry} material={materials.mtl3116927} />
      <mesh geometry={nodes.g_grp3145355.geometry} material={materials.mtl3145355} />
      <mesh geometry={nodes.g_grp3167707.geometry} material={materials.mtl3167707} />
      <mesh geometry={nodes.g_grp3183233.geometry} material={materials.mtl3183233} />
      <mesh geometry={nodes.g_grp3191281.geometry} material={materials.mtl3191281} />
      <mesh geometry={nodes.g_grp3192149.geometry} material={materials.mtl3192149} />
      <mesh geometry={nodes.g_grp3236631.geometry} material={materials.mtl3236631} />
    </group>
  )
}

useGLTF.preload('/scanner.glb')
