/**
 * Canonical 3D focus keys — must stay aligned with backend `FOCUS_KEYS` (backend/index.js)
 * and with `CATEGORY_MATCHES` / `CARD_TITLE_TO_FOCUS` in focusUtils.js.
 */
export const CANONICAL_FOCUS_KEYS = [
  'lung',
  'lungs',
  'left lung',
  'right lung',
  'heart',
  'liver',
  'stomach',
  'pancreas',
  'spleen',
  'thyroid',
  'esophagus',
  'trachea',
  'aorta',
  'kidney',
  'kidneys',
  'left kidney',
  'right kidney',
  'adrenal',
  'left adrenal',
  'right adrenal',
  'colon',
  'duodenum',
  'gallbladder',
  'small bowel',
  'urinary bladder',
  'bladder',
  'prostate',
  'spinal-cord',
  'cervical spine',
  'thoracic spine',
  'lumbar spine',
  'skeleton',
  'bones',
  'clavicle',
  'scapula',
  'humerus',
  'sternum',
  'muscle',
  'iliopsoas',
  'artery',
  'vein',
  'vessel',
  'pulmonary',
  'brachiocephalic',
  'trunk',
  'portal vein',
  'carotid',
  'subclavian',
  'vena cava',
  'brachiocephalic vein',
  'mediastinum',
  'diaphragm',
  'pleura',
  'iliac',
  'femur',
  'hip',
  'gluteus',
  'rib',
  'ribs',
  'vertebra',
  'vertebrae',
  'sacrum',
  'costal cartilage',
];
