/**
 * Segment basenames per anatomy set — generated by `npm run build-segment-sets` → `data/segmentSets.json`.
 */
import segmentSets from './data/segmentSets.json';

export function getSegmentSetIds() {
  return Object.keys(segmentSets).sort((a, b) => a.localeCompare(b));
}

export function getDefaultAnatomySetId() {
  const keys = getSegmentSetIds();
  if (keys.includes('frednonopti')) return 'frednonopti';
  return keys[0] ?? 'frednonopti';
}

export function normalizeAnatomySetId(id) {
  if (id && Array.isArray(segmentSets[id]) && segmentSets[id].length > 0) return id;
  return getDefaultAnatomySetId();
}

/**
 * @param {string} setId
 * @returns {string[]}
 */
export function getSegmentListForSet(setId) {
  const id = normalizeAnatomySetId(setId);
  return segmentSets[id] ?? [];
}

export { segmentSets };
