/**
 * Segment basenames per anatomy set — generated by `npm run build-segment-sets` → `data/segmentSets.json`.
 */
import segmentSets from './data/segmentSets.json';
import { DEFAULT_DICOM_STUDY_ID, getDicomStudyById } from './config/dicomStudies';

export function getSegmentSetIds() {
  return Object.keys(segmentSets).sort((a, b) => a.localeCompare(b));
}

export function getDefaultAnatomySetId() {
  const keys = getSegmentSetIds();
  const fromDefaultStudy = getDicomStudyById(DEFAULT_DICOM_STUDY_ID)?.segmentSetId;
  if (fromDefaultStudy && keys.includes(fromDefaultStudy)) return fromDefaultStudy;
  if (keys.includes('percisio_export')) return 'percisio_export';
  return keys[0] ?? 'percisio_export';
}

export function normalizeAnatomySetId(id) {
  if (id && Array.isArray(segmentSets[id]) && segmentSets[id].length > 0) return id;
  return getDefaultAnatomySetId();
}

/**
 * @param {string} setId
 * @returns {string[]}
 */
export function getSegmentListForSet(setId) {
  const id = normalizeAnatomySetId(setId);
  return segmentSets[id] ?? [];
}

export { segmentSets };
