import { create } from 'zustand';
import { subscribeWithSelector, persist } from 'zustand/middleware';
import { MAX_HISTORY_SIZE } from './utils/historyManager';
import { DEFAULT_DICOM_STUDY_ID, DEFAULT_SCAN_REPORT_ID } from './config/dicomStudies';
import { getDefaultAnatomySetId, normalizeAnatomySetId } from './segmentList';

/**
 * Global store for the 3D scene and Chat.
 * Uses 'subscribeWithSelector' to allow components (like the Chat)
 * to listen to specific state changes (e.g. analyzedReport).
 * Uses 'persist' to keep the conversation state across refreshes.
 */
export const useSceneStore = create(
  subscribeWithSelector(
    persist(
      (set) => ({
        currentFocus: null,
        /** Organ keys from report cards; user can cycle through them. */
        citedOrgans: [],
        citedOrganIndex: 0,
        lastReply: '',
        analyzedReport: null,
        lastCards: [],
        lastMeta: null,
        /** Structured analysis fields from the backend (preferred over regex parsing of lastReply). */
        lastImpression: '',
        lastRecommendations: [],
        /** Currently-selected DICOM study id; null means viewer is locked. */
        selectedDicom: DEFAULT_DICOM_STUDY_ID,
        setSelectedDicom: (dicomId) =>
          set({ selectedDicom: dicomId ?? null }),
        /** Which scan report `.txt` is loaded for the chat (`public/reports/<id>.txt`). Independent from DICOM unless synced on study change. */
        selectedReportId: DEFAULT_SCAN_REPORT_ID,
        setSelectedReportId: (reportId) =>
          set({ selectedReportId: reportId ?? null }),

        /**
         * Subfolder under `public/models/segments/<id>/` (and CDN) for OBJ/MTL.
         * See `src/data/segmentSets.json` (regenerated by `npm run build-segment-sets`).
         */
        anatomySegmentSet: getDefaultAnatomySetId(),
        setAnatomySegmentSet: (id) =>
          set((state) => {
            const next = normalizeAnatomySetId(id);
            if (next === state.anatomySegmentSet) {
              return state;
            }
            return {
              anatomySegmentSet: next,
              segmentVisibility: new Map(),
              modelGroup: null,
              navigationHistory: [],
              historyIndex: -1,
              currentFocus: null,
              pendingCameraRestore: null,
            };
          }),

        segmentVisibility: new Map(), // Map<segmentName, boolean>
        /**
         * Opacity applied to skin (envelope) meshes — see `isSkinSegment` in
         * `Viewer3D/medicalColors.js`. 0 = fully transparent, 1 = opaque.
         * Default low so internal organs stay visible through the skin.
         */
        skinOpacity: 0.15,
        setSkinOpacity: (value) =>
          set(() => {
            const num = Number(value);
            if (!Number.isFinite(num)) return {};
            const clamped = Math.min(1, Math.max(0, num));
            return { skinOpacity: clamped };
          }),
        navigationHistory: [],
        historyIndex: -1,
        conversationHistory: [],

        /** True while the AI is processing (report or chat); used by viewer for desaturation + overlay */
        isAnalyzing: false,
        setAnalyzing: (value) => set({ isAnalyzing: Boolean(value) }),

        // Camera state: getter is set by FocusCamera so history can capture current view
        getCameraState: null,
        setGetCameraState: (fn) => set({ getCameraState: fn }),

        /**
         * Root group of the loaded anatomy model (THREE.Group). Set by
         * `ScannerModel` once all segments are loaded and `centerModelInGroup`
         * has run, so `FocusCamera` can compute a real bounding-box-based
         * default framing instead of relying on hardcoded coordinates. Null
         * while loading or between DICOM switches.
         */
        modelGroup: null,
        setModelGroup: (group) => set({ modelGroup: group ?? null }),

        // When navigating history, set this to the entry's cameraState; FocusCamera applies then clears
        pendingCameraRestore: null,
        setPendingCameraRestore: (state) => set({ pendingCameraRestore: state }),

        // Default camera state (position + target) for "Reset view"; set by FocusCamera when bounds are ready
        getDefaultCameraState: null,
        setGetDefaultCameraState: (fn) => set({ getDefaultCameraState: fn }),

        // Camera orbit: FocusCamera registers a function so the toolbar can rotate
        // the camera (azimuth / polar / roll) while the model stays fixed.
        // Store the fn inside an object so zustand never treats it as a state-updater.
        cameraOrbit: { fn: null },
        setCameraOrbitFn: (fn) => set({ cameraOrbit: { fn: fn ?? null } }),

        // PER-56: in-Canvas snapshot fn for the PDF export (renders one frame
        // then reads the buffer). Wrapped so zustand keeps it as plain data.
        captureViewer: null,
        setCaptureViewer: (fn) => set({ captureViewer: typeof fn === 'function' ? fn : null }),

        // PER-56: multi-angle snapshot fn — orbits the camera and captures N views,
        // restoring the original pose afterwards. Used by the PDF export's 3D grid.
        captureViewerAngles: null,
        setCaptureViewerAngles: (fn) =>
          set({ captureViewerAngles: typeof fn === 'function' ? fn : null }),

        // Auto-spin toggles a continuous azimuthal orbit of the camera in FocusCamera.
        cameraAutoSpin: false,
        setCameraAutoSpin: (value) => set({ cameraAutoSpin: Boolean(value) }),

        // Incremented when camera interaction ends so Viewer3D can push current view to history
        historyPushRequest: 0,
        requestHistoryPush: () =>
          set((s) => ({ historyPushRequest: (s.historyPushRequest || 0) + 1 })),

        setFocus: (organKey) =>
          set({
            currentFocus: organKey,
          }),
        clearFocus: () =>
          set({
            currentFocus: null,
            citedOrgans: [],
            citedOrganIndex: 0,
          }),
        /** Clear zoom/target only; keep citedOrgans from the report for organ cycling. */
        clearCameraFocus: () =>
          set({
            currentFocus: null,
          }),
        /** Set the list of organ keys from report cards; resets index to 0. */
        setCitedOrgans: (organKeys) =>
          set({
            citedOrgans: Array.isArray(organKeys) ? organKeys : [],
            citedOrganIndex: 0,
          }),
        setCitedOrganIndex: (index) =>
          set((state) => {
            const i = Math.max(0, Math.min(index, state.citedOrgans.length - 1));
            const organ = state.citedOrgans[i] ?? null;
            return { citedOrganIndex: i, currentFocus: organ };
          }),
        goToNextCitedOrgan: () =>
          set((state) => {
            if (!state.citedOrgans.length) return state;
            const next = (state.citedOrganIndex + 1) % state.citedOrgans.length;
            return { citedOrganIndex: next, currentFocus: state.citedOrgans[next] };
          }),
        goToPrevCitedOrgan: () =>
          set((state) => {
            if (!state.citedOrgans.length) return state;
            const prev =
              state.citedOrganIndex <= 0
                ? state.citedOrgans.length - 1
                : state.citedOrganIndex - 1;
            return { citedOrganIndex: prev, currentFocus: state.citedOrgans[prev] };
          }),
        setLastReply: (reply) =>
          set({
            lastReply: reply,
          }),
        /**
         * Set report text. When the report content actually changes (new upload),
         * clear findings, organ focus, and conversation so previous reports do not linger.
         */
        setAnalyzedReport: (content) =>
          set((state) => {
            const stored = typeof content === 'string' ? content : null;
            const nextNorm = stored?.trim() ? stored.trim() : '';
            const prevStored = state.analyzedReport;
            const prevNorm =
              typeof prevStored === 'string' && prevStored.trim() ? prevStored.trim() : '';
            const replaced = nextNorm.length > 0 && nextNorm !== prevNorm;

            return {
              analyzedReport: stored,
              ...(replaced
                ? {
                    lastCards: [],
                    lastMeta: null,
                    lastImpression: '',
                    lastRecommendations: [],
                    citedOrgans: [],
                    citedOrganIndex: 0,
                    currentFocus: null,
                    lastReply: '',
                    conversationHistory: [],
                  }
                : {}),
            };
          }),
        setLastCards: (cards) => set({ lastCards: Array.isArray(cards) ? cards : [] }),
        setLastMeta: (meta) => set({ lastMeta: meta }),
        setLastImpression: (text) => set({ lastImpression: typeof text === 'string' ? text : '' }),
        setLastRecommendations: (items) =>
          set({ lastRecommendations: Array.isArray(items) ? items : [] }),
        setSegmentVisibility: (segmentName, visible) =>
          set((state) => {
            const newMap = new Map(state.segmentVisibility);
            newMap.set(segmentName, visible);
            return { segmentVisibility: newMap };
          }),
        setManySegmentVisibility: (entries) =>
          set((state) => {
            const newMap = new Map(state.segmentVisibility);
            if (entries instanceof Map) {
              entries.forEach((visible, segmentName) => {
                newMap.set(segmentName, Boolean(visible));
              });
              return { segmentVisibility: newMap };
            }
            if (entries && typeof entries === 'object') {
              Object.entries(entries).forEach(([segmentName, visible]) => {
                newMap.set(segmentName, Boolean(visible));
              });
            }
            return { segmentVisibility: newMap };
          }),
        toggleSegmentVisibility: (segmentName) =>
          set((state) => {
            const newMap = new Map(state.segmentVisibility);
            const current = newMap.get(segmentName) ?? true;
            newMap.set(segmentName, !current);
            return { segmentVisibility: newMap };
          }),
        setAllSegmentsVisibility: (visible) =>
          set((state) => {
            const newMap = new Map();
            state.segmentVisibility.forEach((_, key) => {
              newMap.set(key, visible);
            });
            return { segmentVisibility: newMap };
          }),
        addToHistory: (state) =>
          set((current) => {
            const newHistory = [...current.navigationHistory];
            if (current.historyIndex < newHistory.length - 1) {
              newHistory.splice(current.historyIndex + 1);
            }
            newHistory.push(state);
            if (newHistory.length > MAX_HISTORY_SIZE) {
              newHistory.shift();
            }
            return {
              navigationHistory: newHistory,
              historyIndex: newHistory.length - 1,
            };
          }),
        navigateHistory: (direction) =>
          set((state) => {
            if (direction === 'back' && state.historyIndex > 0) {
              return { historyIndex: state.historyIndex - 1 };
            }
            if (direction === 'forward' && state.historyIndex < state.navigationHistory.length - 1) {
              return { historyIndex: state.historyIndex + 1 };
            }
            return state;
          }),
        addToConversationHistory: (message) =>
          set((state) => ({
            /* capped so persisted storage cannot grow unbounded */
            conversationHistory: [...state.conversationHistory, message].slice(-80),
          })),
        clearConversationHistory: () =>
          set({
            conversationHistory: [],
          }),
        resetStore: () =>
          set({
            conversationHistory: [],
            analyzedReport: null,
            lastReply: '',
            citedOrgans: [],
            citedOrganIndex: 0,
            currentFocus: null,
            lastCards: [],
            lastMeta: null,
            lastImpression: '',
            lastRecommendations: [],
            selectedDicom: DEFAULT_DICOM_STUDY_ID,
            selectedReportId: DEFAULT_SCAN_REPORT_ID,
            anatomySegmentSet: getDefaultAnatomySetId(),
            segmentVisibility: new Map(),
            skinOpacity: 0.15,
            modelGroup: null,
            navigationHistory: [],
            historyIndex: -1,
            pendingCameraRestore: null,
          }),
      }),
      {
        name: 'percisio-sense-storage',
        /**
         * Bump when the persisted analysis format/content changes so stale
         * cached sessions are dropped and re-analysed fresh:
         *  v2 — moved to LLM-backed English output (regex-era cache was often
         *       in the report's source language).
         *  v3 — chat intro is now a short plain-language orientation (the old
         *       cached intro re-dumped the full structured report).
         *  v4 — the auto-summary moved out of the chat into the Impression
         *       panel; drop threads still carrying the old intro message so the
         *       chat starts empty (PER-51).
         */
        version: 4,
        migrate: (persistedState, fromVersion) => {
          if (!persistedState || fromVersion >= 4) return persistedState;
          return {
            ...persistedState,
            lastReply: '',
            lastCards: [],
            lastMeta: null,
            lastImpression: '',
            lastRecommendations: [],
            conversationHistory: [],
          };
        },
        /**
         * Persist the active case and the conversation so a page refresh
         * restores the session (report, findings, chat thread). Viewer
         * runtime state (camera, visibility, model refs) stays ephemeral.
         */
        partialize: (state) => ({
          selectedDicom: state.selectedDicom,
          selectedReportId: state.selectedReportId,
          anatomySegmentSet: state.anatomySegmentSet,
          analyzedReport: state.analyzedReport,
          conversationHistory: state.conversationHistory,
          lastCards: state.lastCards,
          lastReply: state.lastReply,
          lastMeta: state.lastMeta,
          lastImpression: state.lastImpression,
          lastRecommendations: state.lastRecommendations,
        }),
        merge: (persistedState, currentState) => ({
          ...currentState,
          ...(persistedState ?? {}),
        }),
      }
    )
  )
);


